config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :leads
    end
  end
  root to: "leads#index"

  get "/emails", to: "pages#email"
  get "/assigned_phases", to: "pages#assigned_phases"

  resources :pages, only: [] do
    member do
      patch "accept_phase"
      patch "decline_phase"
    end
  end

  devise_for :users, controllers: { registration: "users/registration" }

  resources :leads do
    resources :phases
  end
  resources :phases do
    resources :comments, module: :phases
  end

  resources :projects do
    resources :comments, module: :projects
  end
  resources :leads do
    resources :comments, module: :leads
  end

  resources :projects do
    member do
      patch "assign_manager", to: "projects#assign_manager"
    end
  end
  resources :phases do
    resources :engineers
  end

  resources :roles, only: [:index] do
    member do
      post :assign_role
      delete :remove_role
    end
  end
end

app/models/lead.rb
# frozen_string_literal: true

# Lead
class Lead < ApplicationRecord
  validates :client_contact, presence: true, numericality: { only_integer: true, message: "must be an integer" }
  validates :project_name, presence: true
  validates :client_name, presence: true

  belongs_to :user, foreign_key: :bd_id

  has_many :phases, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

  has_one :project, dependent: :destroy

  accepts_nested_attributes_for :comments, allow_destroy: true
  scope :sort_by_client, -> { order(:client_name) }

end

app/controllers/api/v1/leads_controller.rb
class Api::V1::LeadsController < Api::V1::ApiBaseController
  before_action :set_lead, only: %i[show update destroy]

  def index
    leads = Lead.all
    if leads.any?
      render json: leads, status: :ok
    else
      error_serializer = ErrorSerializer.new(title: "Lead Not found", status: :not_found)
      render json: error_serializer.to_h,status: :not_found
    end
  end

  def show
    if @lead
      render json: @lead, status: :ok
    else
      error_serializer = ErrorSerializer.new(title: "Lead Not found", status: :not_found)
      render json: error_serializer.to_h,status: :not_found
    end
  end

  def update
    if @lead.update(lead_params)
      render json: @lead, status: :ok
    else
      error_serializer = ErrorSerializer.new(title: "Lead not Update", status: :unprocessable_entity)
      render json: error_serializer.to_h,status: :unprocessable_entity
    end
  end

  def create
    lead = Lead.new(lead_params)
    if lead.save
      render json: lead, status: :created
    else
      error_serializer = ErrorSerializer.new(title: "Lead not Create", status: :unprocessable_entity)
      render json: error_serializer.to_h,status: :unprocessable_entity
    end
  end

  def destroy
    if @lead.nil?
      error_serializer = ErrorSerializer.new(title: "Lead Not found", status: :not_found)
      render json: error_serializer.to_h,status: :not_found
    else
      @lead.destroy
      render json: { message: "Lead deleted successfully" }, status: :ok
    end
  end

  private

  def set_lead
    begin
      @lead = Lead.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error_serializer = ErrorSerializer.new(title: "Lead Not found", status: :not_found)
      render json: error_serializer.to_h,status: :not_found
    end
  end


  def lead_params
    params.require(:lead).permit(:project_name, :client_name, :client_address, :client_email, :client_contact,
                                 :platform_used, :test_type, :bd_id, :sale, :sale_date)
  end
end

app/controllers/leads/comments_controller.rb
# frozen_string_literal: true

class Leads::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Lead.find(params[:lead_id])
  end
end

app/controllers/leads_controller.rb
# frozen_string_literal: true

class LeadsController < ApplicationController
  before_action :set_lead, only: %i[show edit update destroy]

  def index
    @leads = Lead.all

    if params[:query].present?
      @leads = Lead.where(id: search_leads_ids)
    end
    per_page = params[:leads_per_page] || 20
    @leads = @leads.page(params[:page]).per(per_page)
  end

  def search_leads_ids
    @leads = Lead.where(id: LeadsIndex.query(
      query_string: {
        fields: %i[project_name client_email client_name client_contact],
        query: params[:query], default_operator: "and"
      }
    ).load.map(&:id))
  end

  def show
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @lead = Lead.new
    @lead.comments.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @lead = Lead.new(lead_params.merge(bd_id: current_user.id))
    authorize @lead

    if @lead.save
      redirect_to @lead
    else
      flash[:alert] = "Lead details not created: " + @lead.errors.full_messages.join(", ")
      redirect_to @lead
    end
  end


  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @lead = Lead.find(params[:id])
    authorize @lead

    if lead_params[:sale].present?
      if @lead.update(lead_params)
        @project = Project.new(project_name: @lead.project_name, assigned_manager_id: 1, lead_id: @lead.id)
        @project.save

        redirect_to @lead, notice: "Lead details updated successfully."
      else
        redirect_to @lead, alert: "Lead details not updated"
      end
    elsif @lead.update(lead_params.except(:sale))
      redirect_to @lead, notice: "Lead details updated successfully."
    else
      redirect_to @lead, alert: "Lead details not updated"
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    authorize @lead
    @lead.destroy
    redirect_to leads_path
  end

  private

  def set_lead
    begin
      @lead = Lead.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "Lead not found."
      redirect_to leads_path
    end
  end

  def lead_params
    params.require(:lead).permit(:project_name, :client_name, :client_address, :client_email, :client_contact,
                                 :platform_used, :test_type, :bd_id, :sale, :sale_date,comments_attributes: [:id, :content,:commentable_id, :commentable_type,:_destroy])
  end

  def search_params
    params.permit(:query)
  end
end

app/helpers/api/v1/leads_helper.rb
module Api::V1::LeadsHelper
end

app/helpers/leads_helper.rb
# frozen_string_literal: true

module LeadsHelper
end

app/views/leads/_comment_fields.html.erb
<div class="nested-fields">
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= link_to_remove_association 'Remove Comment', f  ,class: "btn btn-primary"%>
</div>

app/views/leads/_edit.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<h1>Edit Lead</h1>
<div class="modal-body">
    <%= render 'form', lead: @lead %>
    </div>
</div>

app/views/leads/_form.html.erb
<%= form_with(model: @lead, remote: true, class: "needs-validation") do |form| %>

  <div class="form-group">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :client_name %>
    <%= form.text_field :client_name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :client_address %>
    <%= form.text_field :client_address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :client_email %>
    <%= form.email_field :client_email, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :client_contact %>
    <%= form.text_field :client_contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :platform_used %>
    <%= form.text_field :platform_used, class: "form-control" %>
  </div>



  <div class="form-group">
    <%= form.label :test_type %>
    <%= form.text_field :test_type, class: "form-control" %>
  </div>

 <div id="comments">
    <%= form.fields_for :comments do |comment_form| %>
      <%= comment_form.hidden_field :commentable_id, value: @lead.id %>
      <%= render 'comment_fields', f: comment_form %>
    <% end %>
  </div>


  <div class="form-actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>

    <%= link_to_add_association 'Add Comment', form, :comments, class: "btn btn-primary", data: {
      association_insertion_node: '#comments', association_insertion_method: :append
    } %>

  </div>
<% end %>

app/views/leads/_new.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


<h1>New Lead</h1>
<div class="modal-body">
    <%= render 'form', lead: @lead %>
    </div>
</div>

app/views/leads/_search_form.html.erb
<div style="display: flex; align-items: flex-start;">
  <%= form_with(url: leads_path, method: :get, html: { style: "display: flex;" }) do |form| %>
    <%= form.text_field :query, class: "form-control", placeholder: "Search Leads", value: params[:query], style: "width: 400px;" %>
    <%= form.submit "Search", class: "btn btn-primary", style: "margin-left: 5px;" %>
    <% if params[:query].present? %>
      <%= link_to 'Clear', leads_path, class: 'btn btn-primary', style: "margin-left: 5px;" %>
    <% end %>
  <% end %>
</div>
<div style="display: flex; justify-content: flex-end; margin-top: -35px;">
  <%= form_tag({ controller: 'leads', action: 'index' }, method: 'get', style: "display: flex;") do %>
    <%= label_tag 'leads_per_page', 'PAGE:',  style: "margin-top: 5px;" %>
    <%= text_field_tag 'leads_per_page', params[:leads_per_page] || 10, type: 'number', min: 1, class: "form-control mr-2", style: "width: 60px;" %>
    <button type="submit" class="btn btn-primary"><i class="fas fa-sync"></i></button>
  <% end %>
</div>

app/views/leads/edit.js.erb
$('#newLeadModal .modal-content').html("<%= j render 'edit', lead: @lead %>");
$('#newLeadModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});

app/views/leads/index.html.erb
<div class="container mt-4">
<%= render 'search_form' %>
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="mb-4">Leads</h1>
      </div>
    </div>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Project Name</th>
        <th>Client Name</th>
        <th>Client Contact</th>
        <th>Client Email</th>
        <th>Sale</th>
        <th>action</th>
        <th>Sale Date</th>
      </tr>
    </thead>
    <tbody>
      <% @leads.each do |lead| %>
        <% presenter = LeadPresenter.new(lead) %>
        <tr>
          <td><%= presenter.project_name %></td>
          <td><%= presenter.client_name %></td>
          <td><%= presenter.client_contact %></td>
          <td><%= presenter.client_email %></td>

          <td>
            <% if presenter.all_phases_completed? %>
              <%= form_with(model: lead, local: true, method: :patch) do |form| %>
                <%= form.check_box :sale %>
                <% if presenter.sale? %>
                  <%= form.hidden_field :sale_date, value: Date.current %>
                  <%= presenter.sale_status %>
                <% else %>
                  <%= form.hidden_field :sale_date, value: nil %>
                   <%= form.submit 'Update Sale status' %>
                <% end %>

              <% end %>
            <% else %>
              <%= presenter.sale_status %>
            <% end %>
            </td>
            <td>
            <div class="btn-group">
                  <%= link_to 'Edit', edit_lead_path(lead), method: :get, remote: true, class: 'btn btn-secondary', data: { toggle: 'modal', target: '#editLeadModal' } %>
                  <%= link_to 'Delete', lead, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
                  <%= link_to 'Show', lead_path(lead), method: :get, class: 'btn btn-danger' %>
                  <%= link_to 'Add Phases', lead_phases_path(lead_id: lead.id), class: 'btn btn-primary' %>
                </div>
          </td>
          <td><%= presenter.completed_status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @leads %>
   <%= button_to 'New Lead', new_lead_path, method: :get, remote: true, class: 'btn btn-primary mt-4', data: { toggle: 'modal', target: '#newLeadModal' } %>


<div class="modal fade" id="newLeadModal" tabindex="-1" role="dialog" aria-labelledby="newLeadModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>
</div>

</div>

app/views/leads/new.js.erb
$('#newLeadModal .modal-content').html("<%= j render 'new', lead: @lead %>");
$('#newLeadModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});

app/views/leads/show.html.erb
<div class="container">
  <h1 class="mt-4"><%= @lead.project_name %></h1>
  <p><strong>Client Name:</strong> <%= @lead.client_name %></p>
  <p><strong>Client Address:</strong> <%= @lead.client_address %></p>
  <p><strong>Client Email:</strong> <%= @lead.client_email %></p>
  <p><strong>Client Contact:</strong> <%= @lead.client_contact %></p>
  <p><strong>Platform Used:</strong> <%= @lead.platform_used %></p>
  <p><strong>Test Type:</strong> <%= @lead.test_type %></p>
  <p><strong>Bd ID:</strong> <%= @lead.bd_id %></p>
  <h2>Comments:</h2>
  <%= render partial: "comments/comments", locals: { commentable: @lead } %>
  <%= render partial: "comments/form", locals: { commentable: @lead } %>
  <%= link_to 'Back', leads_path, class: 'btn btn-secondary' %>
</div>