config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :leads
    end
  end
  root to: "leads#index"

  get "/emails", to: "pages#email"
  get "/assigned_phases", to: "pages#assigned_phases"

  resources :pages, only: [] do
    member do
      patch "accept_phase"
      patch "decline_phase"
    end
  end

  devise_for :users, controllers: { registration: "users/registration" }

  resources :leads do
    resources :phases
  end
  resources :phases do
    resources :comments, module: :phases
  end

  resources :projects do
    resources :comments, module: :projects
  end
  resources :leads do
    resources :comments, module: :leads
  end

  resources :projects do
    member do
      patch "assign_manager", to: "projects#assign_manager"
    end
  end
  resources :phases do
    resources :engineers
  end

  resources :roles, only: [:index] do
    member do
      post :assign_role
      delete :remove_role
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

# Project
class Project < ApplicationRecord
  belongs_to :lead, foreign_key: :lead_id
  belongs_to :user, foreign_key: :assigned_manager_id

  has_many :comments, as: :commentable, dependent: :destroy
  # def initialize(project)
  #   @project = project
  # end

  # def project_name
  #   self.project_name
  # end
end

app/controllers/projects/comments_controller.rb
# frozen_string_literal: true

class Projects::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    begin
      @commentable = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      render plain: "Project not found", status: :not_found
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index

    @projects = Project.all
    if params[:query].present?
      @projects = Project.where(id: ProjectsIndex.query(
        query_string: {
          fields: [:project_name],
          query: params[:query],
          default_operator: "and"
        }
      ).load.map(&:id)).or(Project.where(assigned_manager_id:
        User.where("username LIKE ?", "%#{params[:query]}%")
        .pluck(:id)))
    end
    per_page = (params[:projects_per_page] || 10)
    @projects = @projects.page(params[:page]).per(per_page)


  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: "Project updated successfully."
    else
      render :edit
    end
  end


  def assign_manager
    @project = Project.find(params[:id])
    authorize @project

    if @project.update(assign_manager_params)
      redirect_to root_path, notice: "Project assigned successfully."
    else
      render :edit
    end
  end

  private

  def set_project
    begin
      @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Project not found."
      redirect_to projects_path
    end
  end

  def project_params
    params.require(:project).permit(:project_name, :assigned_manager_id, :lead_id)
  end

  def assign_manager_params
    params.require(:project).permit(:assigned_manager_id)
  end
end

app/controllers/projects_controller.rb, app/controllers/phases_controller.rb, app/controllers/projects/comments_controller.rb, app/controllers/roles_controller.rb, app/controllers/leads_controller.rb, app/controllers/comments_controller.rb, app/controllers/api/v1/api_base_controller.rb
# app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # Eager load associated records
  @projects = Project.includes(:manager, :lead).all

  # Cache result of expensive operation
  @projects = Rails.cache.fetch("projects", expires_in: 5.minutes) do
    Project.all.to_a
  end

  # Extract complex code block into a separate method
  def complex_code_block
    # Code goes here...
  end

  # Use design pattern to simplify code
  class DesignPattern
    # Code goes here...
  end

  # Global exception handler
  rescue_from Exception do |exception|
    # Handle exception...
    logger.error exception.message
  end

  # This is a Javadoc-style comment
  # @param [Type] name description
  # @return [Type] description
  # @raise [ExceptionClass] description
  def method_name
    # Code goes here...
  end

  # This is a class-level comment
  class ClassName
    # This is a method-level comment
    def method_name
      # Code goes here...
    end
  end

  # Linter configuration
  require 'rubocop'
  RuboCop::CLI.new.run

  # Code formatter configuration
  require 'rubocop'
  RuboCop::Formatter::SimpleTextFormatter.new.format
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_edit.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<h1>Edit Project</h1>
<div class="modal-body">
    <%= render 'form', project: @project %>
    </div>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: @project, remote: true, class: "needs-validation") do |form| %>

  <div class="form-group">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_new.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


<h1>New Project</h1>
<div class="modal-body">
    <%= render 'form', project: @project %>
    </div>
</div>

app/views/projects/_search_form.html.erb
<div style="display: flex; align-items: flex-start;">
  <%= form_with(url: projects_path, method: :get, html: { style: "display: flex;" }) do |form| %>
    <%= form.text_field :query, class: "form-control mr-sm-2", placeholder: "Search Project", value: params[:query], style: "width: 400px;" %>
    <%= form.submit "Search", class: "btn btn-primary", style: "margin-left: 5px;" %>
    <% if params[:query].present? %>
      <%= link_to 'Clear', projects_path, class: 'btn btn-primary', style: "margin-left: 5px;" %>
    <% end %>
  <% end %>


</div>
<div style="display: flex; justify-content: flex-end; margin-top: -35px;">
  <%= form_tag({ controller: 'projects', action: 'index' }, method: 'get', style: "display: flex;") do %>
    <%= label_tag 'projects_per_page', 'PAGE:', style: "margin-top: 5px;" %>
    <%= text_field_tag 'projects_per_page', params[:projects_per_page] || 10, type: 'number', min: 1, class: "form-control mr-2" ,style: "width: 60px;" %>
    <button type="submit" class="btn btn-primary"><i class="fas fa-sync"></i></button>
  <% end %>
</div>

app/views/projects/edit.js.erb
$('#newProjectModal .modal-content').html("<%= j render 'edit', project: @project%>");
$('#newProjectModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});

app/views/projects/index.html.erb
<div class="container mt-4">
  <%= render 'search_form' %>
  <div class="container">
    <div class="row">
      <div class="col-12 text-center">
        <h1 class="mb-4">Projects</h1>
      </div>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Project Name</th>
        <th>Edit</th>
        <th>Show</th>
        <th>Select Manager</th>
        <th>Project Manager</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <%# <% presenter = ProjectPresenter.new(project) %>
       <%# <% result = Project.new(project) %>
        <tr>
          <td><%= project.project_name %></td>
          <td>
          <%= link_to 'Edit', edit_project_path(project), method: :get, remote: true, class: 'btn btn-secondary', data: { toggle: 'modal', target: '#newProjectModal' } %>
</td>
<td>
<%= link_to 'show',  project_path(project), class: 'btn btn-primary' %>
</td>
          <td>
          <%= form_with(model: project, url: assign_manager_project_path(project), remote: true, class: "needs-validation") do |form| %>
            <div class="form-group">
              <%= form.label :assigned_manager_id %>
              <%= form.collection_select :assigned_manager_id, Role.find_by(name: "Technical_Manager").users, :id, :username, prompt: "Select Technical Manager", class: "form-control" %>
            </div>
            <%= form.submit "Assign Manager", class: "btn btn-primary ml-2" %>
          <% end %>
        </td>
            <td><%= User.find(project.assigned_manager_id).username %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal fade" id="newProjectModal" tabindex="-1" role="dialog" aria-labelledby="newModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">

      </div>
    </div>
  </div>
  <%= paginate @projects %>
</div>

app/views/projects/new.js.erb
$('#newProjectModal .modal-content').html("<%= j render 'new', project: @project %>");
$('#newProjectModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});

app/views/projects/show.html.erb
<div class="container">
  <h1 class="mt-4"><%= @project.project_name %></h1>
  <p><strong>Assigned Manager ID:</strong> <%= @project.assigned_manager_id %></p>
  <h2>Comments:</h2>
  <%= render partial: "comments/comments", locals: { commentable: @project } %>
  <%= render partial: "comments/form", locals: { commentable: @project } %>
  <%= link_to 'Back', projects_path, class: 'btn btn-secondary' %>
</div>