config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :leads
    end
  end
  root to: "leads#index"

  get "/emails", to: "pages#email"
  get "/assigned_phases", to: "pages#assigned_phases"

  resources :pages, only: [] do
    member do
      patch "accept_phase"
      patch "decline_phase"
    end
  end

  devise_for :users, controllers: { registration: "users/registration" }

  resources :leads do
    resources :phases
  end
  resources :phases do
    resources :comments, module: :phases
  end

  resources :projects do
    resources :comments, module: :projects
  end
  resources :leads do
    resources :comments, module: :leads
  end

  resources :projects do
    member do
      patch "assign_manager", to: "projects#assign_manager"
    end
  end
  resources :phases do
    resources :engineers
  end

  resources :roles, only: [:index] do
    member do
      post :assign_role
      delete :remove_role
    end
  end
end

app/controllers/phases/comments_controller.rb
# frozen_string_literal: true

class Phases::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable

    begin
      @commentable = Phase.find(params[:phase_id])
    rescue ActiveRecord::RecordNotFound
      render plain: "Phase not found", status: :not_found
    end
  end
end

app/controllers/phases_controller.rb
# frozen_string_literal: true

class PhasesController < ApplicationController
  before_action :set_lead
  before_action :set_phase, only: %i[show edit update]

  def index
    @phases = @lead.phases

    if params[:query].present?
      @phases = @lead.phases.where(id: PhasesIndex.query(
        query_string: {
          fields: %w[phase_type completed],
          query: params[:query], default_operator: "AND"
        }
      ).load.map(&:id))
    end

    per_page = (params[:phases_per_page] || 20)
    @phases = @phases.page(params[:page]).per(per_page)
  end

  def new
    @phase = @lead.phases.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @decorated_phase = PhaseDecorator.new(@phase)
  end

  def create
    @phase = @lead.phases.build(phase_params)
    @phase.lead_id = @lead.id
    authorize @phase

    if @phase.save
      PhaseMailer.with(phase: @phase).send_mail.deliver_now
      respond_to do |format|
        format.html { redirect_to lead_phases_path }
        format.js
      end
    else
      redirect_to lead_phases_path, alert: "Phase Detail Not Created"
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @phase.lead_id = @lead.id
    authorize @phase
    if @phase.update(phase_params)

      redirect_to lead_phases_path
    else
      redirect_to lead_phases_path, alert: "Phase Detail Not Updated"
    end
  end

  def destroy
    @phase = Phase.find(params[:id])
    authorize @phase
    @phase.destroy
    redirect_to lead_phases_path
  end

  private

  def set_lead
    begin
      @lead = Lead.find(params[:lead_id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Lead not found."
      redirect_to leads_path
    end
  end

  def set_phase
    begin
      @phase = @lead.phases.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:error] = "Phase not found."
      redirect_to lead_path(@lead)
    end
  end

  def phase_params
    params.require(:phase).permit(:phase_type, :start_date, :due_date, :creation_date, :completed, :completed_date, :assignee_id, :lead_id)
  end
end

app/helpers/phases_helper.rb
# frozen_string_literal: true

module PhasesHelper
end

app/views/phases/_edit.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


<h1>Edit Phase</h1>
<div class="modal-body">
    <%= render 'edit_form', phase: @phase %>
    </div>
</div>

app/views/phases/_edit_form.html.erb
<%= form_with(model: @phase, url: lead_phase_path(@lead, @phase), method: :patch, remote: true, class: "needs-validation") do |form| %>
  <%= form.hidden_field :id %>
<% if current_user.roles.exists?(name: "Business_Developer") %>
  <div class="form-group">
    <%= form.label :phase_type %>
    <%= form.text_field :phase_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control" %>
  </div>



  <div class="form-group">
    <%= form.label :creation_date %>
    <%= form.date_field :creation_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :completed %>
    <%= form.check_box :completed, class: "form-check-input" %>
  </div>

  <div class="form-group">
    <%= form.label :completed_date %>
    <%= form.date_field :completed_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>

  <% elsif current_user.roles.exists?(name: "Technical_Manager") %>
   <div class="form-group">
    <%= form.label :completed %>
    <%= form.check_box :completed, class: "form-check-input" %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
  <% end %>
<% end %>

app/views/phases/_editform.html.erb
<%= form_with(model: @phase, url: lead_phase_path(@lead, @phase), method: :patch, remote: true, class: "needs-validation") do |form| %>
  <%= form.hidden_field :id %>

  <div class="form-group">
    <%= form.label :phase_type %>
    <%= form.text_field :phase_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :creation_date %>
    <%= form.date_field :creation_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :completed %>
    <%= form.check_box :completed, class: "form-check-input" %>
  </div>

  <div class="form-group">
    <%= form.label :completed_date %>
    <%= form.date_field :completed_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/phases/_form.html.erb
<%= form_with(model: @phase, url: lead_phases_path(@lead), remote: true, class: "needs-validation") do |form| %>
  <div class="form-group">
    <%= form.label :phase_type %>
    <%= form.text_field :phase_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :creation_date %>
    <%= form.date_field :creation_date, class: "form-control" %>
  </div>

 <div class="form-group">
  <%= form.label :completed %>
  <%= form.check_box :completed, class: "form-check-input" %>
</div>


  <div class="form-group">
    <%= form.label :completed_date %>
    <%= form.date_field :completed_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/phases/_new.html.erb
<div class="modal-header d-flex justify-content-end">
  <button type="button" class="close btn btn-primary" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>


<h1>New Phase</h1>
<div class="modal-body">
    <%= render 'new_form', phase: @phase %>
    </div>
</div>

app/views/phases/_new_form.html.erb
<%= form_with(model: @phase, url: lead_phases_path(@lead) , remote: true, class: "needs-validation") do |form| %>
  <div class="form-group">
    <%= form.label :phase_type %>
    <%= form.text_field :phase_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :creation_date %>
    <%= form.date_field :creation_date, class: "form-control" %>
  </div>

 <div class="form-group">
  <%= form.label :completed %>
  <%= form.check_box :completed, class: "form-check-input", id: "completed-checkbox" %>
</div>

<div class="form-group">
  <%= form.label :completed_date %>
  <%= form.date_field :completed_date, class: "form-control", id: "completed-date-field", value: Date.today.to_s %>
</div>


<div class="form-group">
  <%= form.label :assignee_id %>
  <%= form.collection_select :assignee_id, Role.find_by(name: "Technical_Manager").users, :id, :username, prompt: "Select Technical Manager", class: "form-control" %>
</div>


  <div class="form-group">
    <%= form.submit "Submit",target: '_blank', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/phases/_newform.html.erb
<%= form_with(model: @phase, url: lead_phases_path(@lead) , remote: true, class: "needs-validation") do |form| %>
  <div class="form-group">
    <%= form.label :phase_type %>
    <%= form.text_field :phase_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comments %>
    <%= form.text_area :comments, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :creation_date %>
    <%= form.date_field :creation_date, class: "form-control" %>
  </div>

 <div class="form-group">
  <%= form.label :completed %>
  <%= form.check_box :completed, class: "form-check-input" %>
</div>


  <div class="form-group">
    <%= form.label :completed_date %>
    <%= form.date_field :completed_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/phases/_search_form.html.erb
<div style="display: flex; align-items: flex-start;">
  <%= form_with(url: lead_phases_path, method: :get, html: { style: "display: flex;" }) do |form| %>
    <%= form.text_field :query, class: "form-control", placeholder: "Search Phase", value: params[:query], style: "width: 400px;" %>
    <%= form.submit "Search", class: "btn btn-primary", style: "margin-left: 5px;" %>
    <% if params[:query].present? %>
      <%= link_to 'Clear', lead_phases_path(lead_id: params['lead_id']), class: 'btn btn-primary', style: "margin-left: 5px;" %>
    <% end %>
  <% end %>
  </div>
 <div style="display: flex; justify-content: flex-end; margin-top: -35px;">
  <%= form_tag({ controller: 'phases', action: 'index' }, method: 'get', style: "display: flex;") do %>
   <%= label_tag 'leads_per_page', 'PAGE:',  style: "margin-top: 5px;" %>
    <%= text_field_tag 'phases_per_page', params[:phases_per_page] || 10, type: 'number', min: 1, class: "form-control mr-2", style: "width: 60px;" %>
    <button type="submit" class="btn btn-primary"><i class="fas fa-sync"></i></button>
  <% end %>
</div>

app/views/phases/edit.js.erb
$('#newPhaseModal .modal-content').html("<%= j render 'edit', phase: @phase %>");
$('#newPhaseModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});

app/views/phases/index.html.erb
<div class="container mt-4">
<%= render 'search_form' %>
 <div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1 class="mb-4">Phases</h1>
    </div>
  </div>
</div>
<div class="table-responsive">
  <table class="table table-bordered">

    <thead>
      <tr>
        <th>Phase Type</th>
        <th>Completed</th>

        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @phases.each do |phase| %>

        <tr>
          <td><%= phase.phase_type %></td>
          <td><%= phase.completed %></td>

          <td>

            <div class="btn-group">
              <%= link_to 'Edit', edit_lead_phase_path(phase.lead, phase), remote: true, class: 'btn btn-secondary', data: { toggle: 'modal', target: '#editPhaseModal' } %>
              <%= link_to 'show',  lead_phase_path(phase.lead, phase), class: 'btn btn-primary' %>
              <%= link_to 'Delete', lead_phase_path(phase.lead, phase), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<%= button_to 'New Phase', new_lead_phase_path, method: :get, remote: true, class: 'btn btn-primary mt-4', data: { toggle: 'modal', target: '#newPhaseModal' } %>


<div class="modal fade" id="newPhaseModal" tabindex="-1" role="dialog" aria-labelledby="newPhaseModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>
<%= paginate @phases %>
<div>

app/views/phases/new.js.erb
$('#newPhaseModal .modal-content').html("<%= j render 'new', phase: @phase %>");
$('#newPhaseModal').modal('show');
$('.modal-header .close').click(function() {
     $('.modal').modal('hide');
});
 $(document).ready(function() {
    $('#completed-checkbox').on('change', function() {
      $('#completed-date-field').prop('disabled', this.checked);
    });
  });

app/views/phases/show.html.erb
<h1>Phase Details</h1>

<div>
  <strong>Phase Type:</strong>
  <%= @phase.phase_type %>
</div>

<div>

  <p>Start Date: <%= @decorated_phase.formatted_start_date %></p>
</div>

<div>
  <strong>Due Date:</strong>
  <%= @phase.due_date %>
</div>



<div>
  <strong>Creation Date:</strong>
  <%= @phase.creation_date %>
</div>

<div>
  <strong>Completed:</strong>
  <%= @phase.completed ? 'Yes' : 'No' %>
</div>

<div>
  <strong>Completed Date:</strong>
  <%= @phase.completed_date %>
</div>
<h2>Comments:</h2>
<%= render partial: "comments/comments", locals: { commentable: @phase } %>
<%= render partial: "comments/form", locals: { commentable: @phase } %>