config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :leads
    end
  end
  root to: "leads#index"

  get "/emails", to: "pages#email"
  get "/assigned_phases", to: "pages#assigned_phases"

  resources :pages, only: [] do
    member do
      patch "accept_phase"
      patch "decline_phase"
    end
  end

  devise_for :users, controllers: { registration: "users/registration" }

  resources :leads do
    resources :phases
  end
  resources :phases do
    resources :comments, module: :phases
  end

  resources :projects do
    resources :comments, module: :projects
  end
  resources :leads do
    resources :comments, module: :leads
  end

  resources :projects do
    member do
      patch "assign_manager", to: "projects#assign_manager"
    end
  end
  resources :phases do
    resources :engineers
  end

  resources :roles, only: [:index] do
    member do
      post :assign_role
      delete :remove_role
    end
  end
end

app/views/layouts/_nav.html.erb
 <nav class="navbar navbar-expand-lg navbar-light" style="background-color:turquoise;">

  <a class="navbar-brand" href="/leads">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">



      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Leads", leads_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "emails", emails_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Projects", projects_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Roles", roles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "assigned_phases", assigned_phases_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-primary" %>
        </li>
        <% if current_user.image.attached? %>
  <div style="position: absolute; top: 0; right: 0;">
    <%= image_tag(current_user.image, style: "display: inline-block; width: 50px; height: 50px; object-fit: cover; border-radius: 50px;") %>
  </div>

<% end %>

      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-primary" %>
        </li>
      <% end %>

    </ul>




  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render 'layouts/nav' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if flash[:error] %>
  <div class="error">
    <%= flash[:error] %>
  </div>
<% end %>
    <%= yield %>

  </body>
</html>

app/views/layouts/application4.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoProject</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>

<body>
  <%= render 'layouts/nav' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if flash[:error] %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>